Add anyOf support #5
manchenkoff/openapi3-parser pull request #49
Opened 2023-01-30 14:22 UTC by yoyossef

oneOf and anyOf seem similar to me, I've added this support as I needed it and that its implementation isn't much different from oneOf from my understanding.

2023-02-04 22:50 UTC, manchenkoff commented
Hey @yoyossef, thanks for your contribution!
Yes, you're right and they are quite the same from a parsing perspective, however, it should be covered in tests as well, so it would be nice to add it if you have time

2023-02-04 22:53 UTC, manchenkoff requested changes
**Request for changes**
Reason - tests are missing

2023-02-15 11:29 UTC, manchenkoff approved these changes

2023-03-30 12:48 UTC, yoyossef commented
I don't know why all commit were named that way, I don't usually use github and make PRs, anyway I believe the build should pass now

2023-03-30 18:08 UTC, manchenkoff approved these changes

2023-04-02 09:11 UTC, merged